trigger: none

pool:
 name: UITestPoolAzure
 
steps:
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'specificVersion'
      testPlatformVersion: '16.11.0'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'WR-VS'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'az disk list'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $tempDirectory = "C:\Temp\Downloads\"
        Remove-Item -Path $tempDirectory -Force -Recurse -ErrorAction Ignore

        $buildId = az pipelines runs list --org https://dev.azure.com/MooDPlatform/ --project MooD --top 10 --query "[?definition.name=='MooD Trunk Nightly Build'].buildNumber | [0]"
        
        Write-Host Downloading build artifacts
        az pipelines runs artifact download --artifact-name CPPTestsZip --path $tempDirectory --run-id $buildId --org https://dev.azure.com/MooDPlatform/ --project MooD
        az pipelines runs artifact download --artifact-name UITestsZip --path $tempDirectory --run-id $buildId --org https://dev.azure.com/MooDPlatform/ --project MooD
        az pipelines runs artifact download --artifact-name MooD --path $tempDirectory --run-id $buildId --org https://dev.azure.com/MooDPlatform/ --project MooD
        
        Write-Host Installing MooD
        $InstallerFilename = "${tempDirectory}MooD17.006.000_BusinessArchitectSetup.exe"
        $processStartInfo = new-object "Diagnostics.ProcessStartInfo"
        $processStartInfo.FileName = $InstallerFilename
        $processStartInfo.Arguments = "/quiet"
        $process = [Diagnostics.Process]::Start($processStartInfo)
        $process.WaitForExit();
        
        Write-Host Extracting CppTests
        Expand-Archive -LiteralPath "${tempDirectory}CppTests.zip" -DestinationPath "C:\Program Files (x86)\MooD\17" -Force
        
        Write-Host Extracting UITests
        Expand-Archive -LiteralPath "${tempDirectory}UITests.zip" -DestinationPath "C:\Program Files (x86)\MooD\17" -Force
  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'specific'
      width: '1920'
      height: '1080'
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: 'C:\Program Files (x86)\MooD\17\Test_UI.dll'
      #testFiltercriteria: 'Name~ActionPanelsButtonCloseWindow'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: 'C:\Temp\TestResults'
      uiTests: true
      vstestLocationMethod: 'location'
      vstestLocation: 'C:\Users\testuser\Desktop\microsoft.testplatform.16.0.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'
      publishRunAttachments: false
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'