# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
   name: UITestPoolAzure

jobs:
  - job: Test
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'WR-VS'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            "1","2" | ForEach-Object -Parallel { 
              az vm start --resource-group test-resource-group --name par-test-$_ 
            } -ThrottleLimit 4
            
            Start-Sleep -Seconds 30

            Invoke-Command -ComputerName @('10.0.0.6','10.0.0.7') -ScriptBlock {
              Start-ScheduledTask -TaskName "Run Tests"
              do{
                  $state = Get-ScheduledTask -TaskName "Run Tests"|select -expand State
                  Start-Sleep -Milliseconds 500
              } while($state -eq "Running")
            }
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '*.trx'
          searchFolder: 'C:/Shared/'
          mergeTestResults: true
