trigger: none

pool:
 name: UITestPoolAzure
 
steps:
  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'specific'
      width: '1920'
      height: '1080'
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '"C:\Program Files (x86)\MooD\17\Test_UI.dll"'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: 'C:\Temp\TestResults'
      uiTests: true
      vstestLocationMethod: 'location'
      vstestLocation: 'C:\Users\testuser\Desktop\microsoft.testplatform.16.0.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'
      publishRunAttachments: false