trigger: none

pool:
  vmImage: 'windows-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'WR-VS'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $resourceGroup = "test-resource-group"
        $restoreCollection = "Test"
        $vmName = "manual-test-vm"
        
        $newDiskName = [guid]::NewGuid()
        
        $osDiskRestorePoint = az restore-point show --resource-group $resourceGroup --collection-name $restoreCollection --name "Test-rp-2023-12-04-09-44-49" --query "sourceMetadata.storageProfile.osDisk.diskRestorePoint.id"
         
        Write-Host Got restore point
        
        $oldOSDiskName = az vm show --resource-group $resourceGroup -n $vmName --query "storageProfile.osDisk.name"
        
        Write-Host "Got old disk name: $oldOSDiskName"
        
        az disk create --resource-group $resourceGroup --name $newDiskName --sku Premium_LRS --size-gb 128 --source $osDiskRestorePoint --zone 1
        
        Write-Host Created disk
        
        az vm update -g $resourceGroup -n $vmName --os-disk $newDiskName
        
        Write-Host Updated OS disk
        
        az disk delete --resource-group $resourceGroup --name $oldOSDiskName --yes
        
        Write-Host Deleted old disk