trigger: none

pool:
  vmImage: 'windows-latest'

jobs:
- deployment: VMDeploy
  displayName: Deploy to test VM
  environment: 
   name: TestVM
   resourceName: manual-test-vm
   resourceType: virtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"