# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
   name: UITestPoolAzure

jobs:
  - job: Test
    timeoutInMinutes: 180
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '20.x'
          checkLatest: true
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'install chromedriver --detect_chromedriver_version'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $sharedDirectory = "C:\Shared"

            Write-Host Deleting old files
            Get-ChildItem -Path $sharedDirectory | ForEach-Object -Process { 
              if($_.attributes -eq "Directory") {
                Remove-Item -Path $_.FullName -Recurse -Force
              } else {
                Remove-Item -Path $_.FullName -Force
              }
            }
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)/s/node_modules/chromedriver/lib/chromedriver'
          Contents: 'chromedriver.exe'
          TargetFolder: 'C:/Shared'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'MD-VS'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $env:AZURE_DEVOPS_EXT_PAT = "$(System.AccessToken)"
            $numMachines = 2
            
            Write-Host Deleting VMs
            az vm delete -g ui-tests -n vm-ui-tests-1 --force-deletion true --yes
            az vm delete -g ui-tests -n vm-ui-tests-2 --force-deletion true --yes
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '*.trx'
          searchFolder: 'C:/Shared/'
          mergeTestResults: true
