# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
- cron: '0 22 * * 1-5'
  always: true
  displayName: Overnight run
  branches:
    include:
    - main

pool:
   name: UITestPoolAzure

parameters:
- name: numMachines
  displayName: Number of Machines (max 8)
  type: number
  default: 8
  values:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
- name: deleteVMs
  displayName: Delete VMs at end of run
  type: boolean
  default: true
- name: cleanOnly
  displayName: Clean only (delete any VMs and don't run tests)
  type: boolean
  default: false
- name: testCaseFilters
  displayName: Test case filters (per machine)
  type: object
  default: 
    Delete this line and specify a list of filters like so to run specific test cases (each line is run its own VM up to the max):
    testCaseFilters:
    - Name~Variable
    - Name~Matrix|Name~Matrices

variables:
- name: resourceGroup
  value: ui-tests
- name: vmPrefix
  value: ui-tests-vm- 

jobs:
  - job: Test
    timeoutInMinutes: 180
    steps:
      - ${{ if eq(parameters.cleanOnly, false) }}:
        - task: NodeTool@0
          displayName: Install Node
          inputs:
            versionSource: 'spec'
            versionSpec: '20.x'
            checkLatest: true
        - task: Npm@1
          displayName: Download Chromedriver
          inputs:
            command: 'custom'
            customCommand: 'install chromedriver --detect_chromedriver_version'
        - task: PowerShell@2
          displayName: Delete old files
          inputs:
            targetType: 'inline'
            script: |
              $sharedDirectory = "C:\Shared"

              Write-Host Deleting old files
              Get-ChildItem -Path $sharedDirectory | ForEach-Object -Process { 
                if($_.attributes -eq "Directory") {
                  Remove-Item -Path $_.FullName -Recurse -Force
                } else {
                  Remove-Item -Path $_.FullName -Force
                }
              }
        - task: CopyFiles@2
          displayName: Copy Chromedriver to shared folder
          inputs:
            SourceFolder: '$(Agent.BuildDirectory)/s/node_modules/chromedriver/lib/chromedriver'
            Contents: 'chromedriver.exe'
            TargetFolder: 'C:/Shared'
        - task: AzureCLI@2
          displayName: Setup and run tests
          env:
            numMachines: ${{ parameters.numMachines }}
          inputs:
            azureSubscription: 'MD-VS'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $env:AZURE_DEVOPS_EXT_PAT = "$(System.AccessToken)"
              $numMachines = $env:numMachines
              $hostIp = ""+(Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Ethernet 5").IPAddress
              $sharedDir = "\\$hostIp\Shared"
              $buildDir = "$sharedDir\Build"
              $uiTestsDir = "$buildDir\UITests"
              $localSharedDir = "C:\Shared"
              $localBuildDir = "$localSharedDir\Build"
              $localUiTestsDir = "$localBuildDir\UITests"
              $vstest = "C:\Users\testuser\Desktop\TestPlatform\vstest.console.exe"
              $orgUrl = "https://dev.azure.com/MooDPlatform/"
              $projectName = "MooD"
              $resourceGroup = "$(resourceGroup)"
              $vmPrefix = "$(vmPrefix)"
              $vmImageUrl = "/subscriptions/0c8dec2a-b188-4313-a3e2-70f255ada0b9/resourceGroups/ui-tests/providers/Microsoft.Compute/galleries/UITestsGallery/images/UITestsDefinition"
              $vmUser = "testuser"
              $vmPassword = "Ts0rg123_Ts0rg123"
              $moodDir = "C:\Program Files (x86)\MooD\17"
              $testCaseFiltersJson = '${{ convertToJson(parameters.testCaseFilters) }}' | ConvertFrom-Json

              Write-Host Ensuring old VMs are deleted
              1..10 | ForEach-Object -Parallel { 
                  az vm delete -g $using:resourceGroup -n "$($using:vmPrefix)${_}" --force-deletion true --yes --force-deletion true --yes
              } -ThrottleLimit 10

              Write-Host Downloading latest build artifacts
              Write-Host Getting build id
              $buildId = az pipelines runs list --org $orgUrl --project $projectName --query "[?definition.name=='MooD Trunk Nightly Build'].buildNumber | [0]"
              az pipelines runs artifact download --artifact-name CPPTestsZip --path $buildDir --run-id $buildId --org $orgUrl --project $projectName
              az pipelines runs artifact download --artifact-name UITestsZip --path $buildDir --run-id $buildId --org $orgUrl --project $projectName
              az pipelines runs artifact download --artifact-name MooD --path $buildDir --run-id $buildId --org $orgUrl --project $projectName

              $testCaseFilters = [System.Collections.ArrayList]@()
              $testCaseFiltersProvided = $testCaseFiltersJson.PSobject.Properties.Name.Count -eq 1

              if ($testCaseFiltersProvided) {
                Write-Host Using provided test case filters
                $testCaseFilters = [System.Collections.ArrayList]@()
                $testCaseFiltersJson.testCaseFilters | ForEach-Object { 
                  $testCaseFilters.Add($_) | Out-Null
                }
                $numMachines = $testCaseFilters.Count
              } else {
                Write-Host Extracting UITests locally
                Expand-Archive -LiteralPath "${buildDir}\UITests.zip" -DestinationPath $uiTestsDir -Force

                Write-Host Listing test names
                $testNamesFile = "$localBuildDir\TestNames.txt"
                & $vstest "$localUiTestsDir\Test_UI.dll" /ListFullyQualifiedTests "/ListTestsTargetPath:${testNamesFile}"
                $tests = Get-Content $testNamesFile

                Write-Host Splitting tests per VM
                $splitTests = @($null) * $numMachines
                0..($numMachines - 1) | ForEach-Object { $splitTests[$_] = [System.Collections.Generic.List[string]]::new() }
                0..($tests.Length - 1) | ForEach-Object { $splitTests[$_ % $numMachines].Add($tests[$_]) }
                0..($splitTests.Length - 1) | ForEach-Object { $splitTests[$_] = $splitTests[$_] -join '|' }
                0..($splitTests.Length - 1) | ForEach-Object { $testCaseFilters.Add($splitTests[$_]) }
              }

              Write-Host Test case filters:
              1..$numMachines | ForEach-Object { 
                  Write-Host VM"$_": $testCaseFilters[$_ - 1]
              }

              Write-Host Creating $numMachines VMs
              1..$numMachines | ForEach-Object -Parallel { 
                  az vm create --resource-group $using:resourceGroup --name "$($using:vmPrefix)${_}" --image $using:vmImageUrl --specialized --license-type Windows_Client --admin-password $using:vmPassword --admin-username $using:vmUser --security-type TrustedLaunch --size Standard_D2s_v3 --public-ip-address '""' --os-disk-delete-option delete --nic-delete-option delete
              } -ThrottleLimit $numMachines

              Write-Host Getting VM ips
              $ips = [System.Collections.ArrayList]@()
              1..$numMachines | ForEach-Object { 
                  $ip = az vm list-ip-addresses --resource-group $resourceGroup --name "${vmPrefix}${_}" --query [0].virtualMachine.network.privateIpAddresses[0] 
                  $ips.Add($ip.Replace('"', '')) | Out-Null
              }

              Write-Host Sleeping for 210 seconds to let VMs boot
              Start-Sleep -Seconds 210

              Write-Host Trusting VM ips
              $ipsStr = $ips -join ','
              $ipsStr = '"' + $ipsStr + '"'
              winrm set winrm/config/client "@{TrustedHosts=$ipsStr}"

              $script = @"
              `$tempDir = "C:\Temp"
              `$tempBuildDir = "`$tempDir\Build"

              Write-Host Copying setup files locally
              Copy-item -Path $sharedDir -Destination `$tempDir -Recurse

              Write-Host Finding BA installer
              `$results = Get-ChildItem -Path `$tempBuildDir |
                Where-Object Name -match ".*BusinessArchitectSetup.exe" | 
                Select-Object FullName
              `$installerFilename = `$results[0].FullName

              Write-Host Installing MooD
              `$processStartInfo = new-object "Diagnostics.ProcessStartInfo"
              `$processStartInfo.FileName = `$installerFilename
              `$processStartInfo.Arguments = "/quiet"
              `$process = [Diagnostics.Process]::Start(`$processStartInfo)
              `$process.WaitForExit();
                  
              Write-Host Extracting CppTests
              Expand-Archive -LiteralPath "`$tempBuildDir\CppTests.zip" -DestinationPath "$moodDir" -Force
                              
              Write-Host Extracting UITests
              Expand-Archive -LiteralPath "`$tempBuildDir\UITests.zip" -DestinationPath "$moodDir" -Force

              Write-Host Replacing Chromedriver
              Copy-item -Path "`$tempDir\chromedriver.exe" -Destination "$moodDir"

              Write-Host Installing licence
              [microsoft.win32.registry]::SetValue("HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\MooD International\Licence\17.0", "licencepath", "`$tempBuildDir\Internallicence.xml")

              Write-Host Creating rep
              & "$moodDir\MooDRepositoryManager.com" addserver /server localhost 
              & "$moodDir\MooDRepositoryManager.com" create /server "localhost" /name "17Test1a"

              `$env:CAPTUREOVERNIGHTOUTPUT='yes'
              `$env:OVERNIGHTOUTPUTDIR='$sharedDir'
              "@

              $jobs = [System.Collections.ArrayList]@()

              Write-Host Starting tests
              for ($i = 0; $i -lt $numMachines; $i++) {
                  $job = Invoke-Command -ComputerName $ips[$i] -ScriptBlock {
                      $testScriptFile = "C:\Users\testuser\Desktop\RunTests.ps1"
                      $taskName = "Run UI Tests"
                      $resultsDir = "C:\Temp\Res"
                      $i = $args[1] + 1
                      $tests = $args[2]

                      Out-File -FilePath $testScriptFile -InputObject $args[0]
                      
                      $vstestCmd = '& ' + "$using:vstest" + ' "' + $using:moodDir + '\Test_UI.dll" "/TestCaseFilter:' + "$tests" + '" "/Logger:trx;LogFileName=' + $using:sharedDir + '\Tests_' + "$i" + '.trx"' + ' /ResultsDirectory:' + "$resultsDir"
                      Add-Content -Path $testScriptFile -Value $vstestCmd

                      $copyResultFiles = 'Copy-Item ' + "$resultsDir" + '\* -Destination ' + "$using:sharedDir" + ' -Recurse -Force'
                      Add-Content -Path $testScriptFile -Value $copyResultFiles

                      $action= New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-File $testScriptFile"
                      Register-ScheduledTask -TaskName $taskName -User testuser -Action $action -RunLevel Highest -Force

                      Start-ScheduledTask -TaskName $taskName
                      do {
                          $state = Get-ScheduledTask -TaskName $taskName | Select-Object -expand State
                          Start-Sleep -Milliseconds 500
                      } while ($state -eq "Running")
                  } -AsJob -ArgumentList @($script, $i, $testCaseFilters[$i])

                  $jobs.Add($job) | Out-Null
              }

              Write-Host Waiting for tests to finish
              $jobs | Receive-Job -Wait -AutoRemoveJob

              Write-Host Updating machine name for tests
              1..$numMachines | ForEach-Object -Parallel { 
                  $resultsFile = "$using:sharedDir\Tests_$_.trx"
                  $xml = [xml](Get-Content -Path $resultsFile)
                  $nodes = $xml.SelectNodes("//*[@computerName]");
                  foreach($node in $nodes) {
                      $node.SetAttribute("computerName", "VM $_");
                  }
                  $xml.Save($resultsFile)
              } -ThrottleLimit $numMachines
        - task: PublishTestResults@2
          displayName: Publish test results
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '*.trx'
            searchFolder: 'C:/Shared/'
            mergeTestResults: true
        - task: AzureCLI@2
          enabled: false
          displayName: Upload test files
          inputs:
            azureSubscription: 'MD-VS'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $hostIp = ""+(Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Ethernet 5").IPAddress
              $sharedDir = "\\$hostIp\Shared"
              $maxDate = (Get-Date).AddDays(1).ToString("yyyy-MM-dd")
              $minDate = (Get-Date).AddDays(-3).ToString("yyyy-MM-dd")
              $headers = "Authorization=Bearer $(System.AccessToken)"

              $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/runs?minLastUpdatedDate="'+"$minDate"+'"&maxLastUpdatedDate="'+"$maxDate"+'"&buildIds=$(Build.BuildId)&api-version=6.0"'
              $res = az rest --method get --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url --headers $headers
              Write-Host $res
              $res = $res | ConvertFrom-Json

              $testRunId = $res.value[0].id
              Write-Host $testRunId

              $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/runs/"'+"$testRunId"+'"/results?api-version=6.0"'
              $res = az rest --method get --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url --headers $headers
              Write-Host $res
              $res = $res | ConvertFrom-Json

              foreach ($value in $res.value) {
                  $fileName = $value.testCaseTitle + '.log'
                  $logFile = "$sharedDir/" + $fileName
                  $tempJsonFile = "C:\temp\file.json"

                  Write-Host $fileName
                  if ((Test-Path $logFile) -and ([String]::IsNullOrWhiteSpace((Get-content $logFile)) -eq $false)) {
                      Write-Host $logFile
                      $fileStream = [convert]::ToBase64String((Get-Content -path $logFile -Encoding byte))
                      $testId = $value.id
                      $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/Runs/"'+"$testRunId"+'"/Results/"'+"$testId"+'"/attachments?api-version=7.1-preview.1"'
                      $body = (@{
                          stream=$fileStream;
                          fileName=$fileName;
                          comment="Log";
                          attachmentType="GeneralAttachment"
                      } | ConvertTo-Json -Compress) | Out-File $tempJsonFile

                      az rest --method post --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url --body "@$tempJsonFile" --headers $headers
                  }

                  $fileName = $value.testCaseTitle + '.png'
                  $imgFile = "$sharedDir/" + $fileName
                  Write-Host $fileName
                  if ((Test-Path $imgFile) -and ([String]::IsNullOrWhiteSpace((Get-content $imgFile)) -eq $false)) {
                      Write-Host $imgFile
                      $fileStream = [convert]::ToBase64String((Get-Content -path $imgFile -Encoding byte))
                      $testId = $value.id
                      $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/Runs/"'+"$testRunId"+'"/Results/"'+"$testId"+'"/attachments?api-version=7.1-preview.1"'
                      $body = (@{
                          stream=$fileStream;
                          fileName=$fileName;
                          comment="Screenshot";
                          attachmentType="GeneralAttachment"
                      } | ConvertTo-Json -Compress) | Out-File $tempJsonFile

                      az rest --method post --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url --body "@$tempJsonFile" --headers $headers
                  }
              }
      - ${{ if or(eq(parameters.deleteVMs, true), eq(parameters.cleanOnly, true)) }}:
        - task: AzureCLI@2
          displayName: Delete VMs
          inputs:
            azureSubscription: 'MD-VS'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $env:AZURE_DEVOPS_EXT_PAT = "$(System.AccessToken)"
              $resourceGroup = "$(resourceGroup)"
              $vmPrefix = "$(vmPrefix)"

              Write-Host Deleting VMs
              1..10 | ForEach-Object -Parallel { 
                  az vm delete -g $using:resourceGroup -n "$($using:vmPrefix)${_}" --no-wait --force-deletion true --yes
              } -ThrottleLimit 10
