trigger: none

resources:
  pipelines:
  - pipeline: Setup Pipeline
    source: UI Tests - Reset Machine
    trigger: true

pool:
 name: UITestPoolAzure

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
      checkLatest: true
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install chromedriver --detect_chromedriver_version'
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'specificVersion'
      testPlatformVersion: '16.11.0'
  
  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'specific'
      width: '1920'
      height: '1080'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.BuildDirectory)/s/node_modules/chromedriver/lib/chromedriver'
      Contents: '**'
      TargetFolder: 'C:/Program Files (x86)/MooD/17'
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: 'C:\Program Files (x86)\MooD\17\Test_UI.dll'
      #testFiltercriteria: 'Name~DataTables'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: 'C:\Temp\TestResults'
      uiTests: true
      #vsTestVersion: 'toolsInstaller'
      vstestLocationMethod: 'location'
      vstestLocation: 'C:\Users\testuser\Desktop\TestPlatform\vstest.console.exe'
      publishRunAttachments: true
  
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'
  