# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
   name: UITestPoolAzure

jobs:
  - job: Test
    timeoutInMinutes: 180
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '20.x'
          checkLatest: true
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'install chromedriver --detect_chromedriver_version'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $sharedDirectory = "C:\Shared"

            Write-Host Deleting old files
            Get-ChildItem -Path $sharedDirectory | ForEach-Object -Process { 
              if($_.attributes -eq "Directory") {
                Remove-Item -Path $_.FullName -Recurse -Force
              } else {
                Remove-Item -Path $_.FullName -Force
              }
            }
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)/s/node_modules/chromedriver/lib/chromedriver'
          Contents: 'chromedriver.exe'
          TargetFolder: 'C:/Shared'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'MD-VS'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $env:AZURE_DEVOPS_EXT_PAT = "$(System.AccessToken)"
            $numMachines = 2
            $sharedDirectory = "C:\Shared"
            $targetDirectory = "$sharedDirectory\Build"
            $targetDirectory2 = "\\10.0.0.4\Shared\Build"
            $uitestsDirectory = "${targetDirectory}\UITests"
            $vstest = "C:\Users\testuser\Desktop\TestPlatform\vstest.console.exe"


            Write-Host Creating VMs
            1..$numMachines | ForEach-Object -Parallel { 
              az vm create --resource-group ui-tests --name vm-ui-tests-$_ --image "/subscriptions/0c8dec2a-b188-4313-a3e2-70f255ada0b9/resourceGroups/ui-tests/providers/Microsoft.Compute/galleries/UITestsGallery/images/UITestsDefinition" --specialized --license-type Windows_Client --admin-password Ts0rg123_Ts0rg123 --admin-username testuser --security-type TrustedLaunch --size Standard_D2s_v3 --public-ip-address '""' --os-disk-delete-option delete --nic-delete-option delete
            } -ThrottleLimit $numMachines

            
            Write-Host Deleting VMs
            1..$numMachines | ForEach-Object -Parallel { 
              az vm delete -g ui-tests -n vm-ui-tests-$_ --force-deletion true --yes --force-deletion true --yes
            } -ThrottleLimit $numMachines
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '*.trx'
          searchFolder: 'C:/Shared/'
          mergeTestResults: true
