trigger: none

resources:
  pipelines:
  - pipeline: Setup Pipeline
    source: UI Tests - Reset Machine
    trigger: true

pool:
 name: UITestPoolAzure

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
      checkLatest: true
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install chromedriver --detect_chromedriver_version'
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'specificVersion'
      testPlatformVersion: '16.11.0'

  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'specific'
      width: '1920'
      height: '1080'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.BuildDirectory)/s/node_modules/chromedriver/lib/chromedriver'
      Contents: '**'
      TargetFolder: 'C:/Program Files (x86)/MooD/17'
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: 'C:\Program Files (x86)\MooD\17\Test_UI.dll'
      testFiltercriteria: 'Name~DataTables'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: 'C:\Temp\TestResults'
      uiTests: true
      #vsTestVersion: 'toolsInstaller'
      vstestLocationMethod: 'location'
      vstestLocation: 'C:\Users\testuser\Desktop\TestPlatform\vstest.console.exe'
      publishRunAttachments: true
    continueOnError: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'WR-VS'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $maxDate = Get-Date -Format "yyyy-MM-dd"
        $minDate = (Get-Date).AddDays(-3).ToString("yyyy-MM-dd")

        $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/runs?minLastUpdatedDate="'+"$minDate"+'"&maxLastUpdatedDate="'+"$maxDate"+'"&buildIds=26760&api-version=6.0"'
        $res = az rest --method get --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url --headers "Authorization=Bearer $(System.AccessToken)"
        Write-Host $res
        $res = $res | ConvertFrom-Json

        $testRunId = $res.value[0].id

        $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/runs/1000052/results?api-version=6.0"'
        $res = az rest --method get --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url
        $res = $res | ConvertFrom-Json

        foreach ($value in $res.value) {
            $fileName = 'StdOut_' + $value.testCaseTitle + '.log'
            $logFile = 'C:/Temp/TestLogs/' + $fileName
            if (Test-Path $logFile) {
                $fileStream = [convert]::ToBase64String((Get-Content -path $logFile -Encoding byte))
                $testId = $value.id
                $url = '"https://dev.azure.com/MooDPlatform/MooD/_apis/test/Runs/"'+"$testRunId"+'"/Results/"'+"$testId"+'"/attachments?api-version=7.1-preview.1"'
                $body = (@{
                    stream=$fileStream;
                    fileName=$fileName;
                    comment="Log";
                    attachmentType="GeneralAttachment"
                } | ConvertTo-Json -Compress).Replace('"', '\"')

                az rest --method post --resource 499b84ac-1321-427f-aa17-267ca6975798 --url $url --body $body
            }
        }
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'
  