trigger: none

schedules:
- cron: '30 14 * * 1-5'
  always: true
  displayName: Overnight run
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'WR-VS'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $resourceGroup = "test-resource-group"
        $restoreCollection = "Test"
        $vmName = "manual-test-vm"
        $restorePointName = "ui-tests-rp"

        $newDiskName = [guid]::NewGuid()

        $osDiskRestorePoint = az restore-point show --resource-group $resourceGroup --collection-name $restoreCollection --name $restorePointName --query "sourceMetadata.storageProfile.osDisk.diskRestorePoint.id"
        
        Write-Host Got restore point

        $oldOSDiskName = az vm show --resource-group $resourceGroup -n $vmName --query "storageProfile.osDisk.name"

        Write-Host "Got old disk name: $oldOSDiskName"

        az disk create --resource-group $resourceGroup --name $newDiskName --sku Premium_LRS --size-gb 128 --source $osDiskRestorePoint --zone 1

        Write-Host Created disk

        az vm update -g $resourceGroup -n $vmName --os-disk $newDiskName

        Write-Host Starting VM

        az vm start -g $resourceGroup -n $vmName --no-wait

        Write-Host Updated OS disk

        az disk delete --resource-group $resourceGroup --name $oldOSDiskName --yes

        Write-Host Deleted old disk