trigger: none

resources:
  pipelines:
  - pipeline: Setup Pipeline
    source: UI Tests - Reset Machine
    trigger: true

pool:
 name: UITestPoolAzure

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
      checkLatest: true
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install chromedriver --detect_chromedriver_version'
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'specificVersion'
      testPlatformVersion: '16.11.0'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'WR-VS'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $env:AZURE_DEVOPS_EXT_PAT = "$(System.AccessToken)"
        $tempDirectory = "C:\Temp\Downloads\"
        Remove-Item -Path $tempDirectory -Force -Recurse -ErrorAction Ignore
        $buildId = az pipelines runs list --org https://dev.azure.com/MooDPlatform/ --project MooD --query "[?definition.name=='MooD Trunk Nightly Build'].buildNumber | [0]"
        
        Write-Host Downloading build artifacts
        az pipelines runs artifact download --artifact-name CPPTestsZip --path $tempDirectory --run-id $buildId --org https://dev.azure.com/MooDPlatform/ --project MooD
        az pipelines runs artifact download --artifact-name UITestsZip --path $tempDirectory --run-id $buildId --org https://dev.azure.com/MooDPlatform/ --project MooD
        az pipelines runs artifact download --artifact-name MooD --path $tempDirectory --run-id $buildId --org https://dev.azure.com/MooDPlatform/ --project MooD
        
        Write-Host Installing MooD
        $InstallerFilename = "${tempDirectory}MooD17.006.000_BusinessArchitectSetup.exe"
        $processStartInfo = new-object "Diagnostics.ProcessStartInfo"
        $processStartInfo.FileName = $InstallerFilename
        $processStartInfo.Arguments = "/quiet"
        $process = [Diagnostics.Process]::Start($processStartInfo)
        $process.WaitForExit();
        
        Write-Host Extracting CppTests
        Expand-Archive -LiteralPath "${tempDirectory}CppTests.zip" -DestinationPath "C:\Program Files (x86)\MooD\17" -Force
        
        Write-Host Extracting UITests
        Expand-Archive -LiteralPath "${tempDirectory}UITests.zip" -DestinationPath "C:\Program Files (x86)\MooD\17" -Force
  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'specific'
      width: '1920'
      height: '1080'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.BuildDirectory)/s/node_modules/chromedriver/lib/chromedriver'
      Contents: '**'
      TargetFolder: 'C:/Program Files (x86)/MooD/17'
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: 'C:\Program Files (x86)\MooD\17\Test_UI.dll'
      #testFiltercriteria: 'Name~DataTables'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: 'C:\Temp\TestResults'
      uiTests: true
      #vsTestVersion: 'toolsInstaller'
      vstestLocationMethod: 'location'
      vstestLocation: 'C:\Users\testuser\Desktop\TestPlatform\vstest.console.exe'
      publishRunAttachments: true
  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'
  